import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc } from 'firebase/firestore';
import { BarChart3, Boxes, ChevronRight, CircleDollarSign, ExternalLink, LayoutDashboard, PackagePlus, Pencil, Plus, Search, ShoppingBag, Trash2, X } from 'lucide-react';
import { db, isFirebaseConfigured } from './firebase';
import * as XLSX from 'xlsx';
import axinopLogo from './assets/axinop-logo.png';
import './styles.css';
import './contrast.css';

let saleCrud = {};
let investmentSales = [];

const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 });
const blank = { name:'', category:'', sku:'', stock:0, cost:0, price:0, imageUrl:'', sourceUrl:'' };
const seed = [{id:'A00001',name:'Multicontactos USB',category:'USB',sku:'A00001',stock:4,cost:51.2,price:100,imageUrl:'',sourceUrl:''},{id:'A00004',name:'Audífonos negros',category:'Inalámbricos',sku:'A00004',stock:15,cost:47.68,price:100,imageUrl:'',sourceUrl:''},{id:'A00009',name:'Mouse pilas',category:'Inalámbricos / Pilas',sku:'A00009',stock:2,cost:58.7,price:100,imageUrl:'',sourceUrl:''}];
function App(){
 const [products,setProducts]=useState([]),[sales,setSales]=useState([]),[section,setSection]=useState('Resumen'),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[detail,setDetail]=useState(null),[productOpen,setProductOpen]=useState(false),[saleOpen,setSaleOpen]=useState(false),[exportOpen,setExportOpen]=useState(false);
 investmentSales=sales;
 useEffect(()=>{if(!db){setProducts(seed);return;}const p=onSnapshot(query(collection(db,'products'),orderBy('createdAt','desc')),s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()}))));const v=onSnapshot(query(collection(db,'sales'),orderBy('createdAt','desc')),s=>setSales(s.docs.map(d=>({id:d.id,...d.data()}))));return()=>{p();v();};},[]);
 const metrics=useMemo(()=>{const availableCost=products.reduce((n,p)=>n+(+p.stock||0)*(+p.cost||0),0),soldCost=sales.reduce((n,s)=>n+(+s.costTotal||0),0),investment=availableCost+soldCost,revenue=sales.reduce((n,s)=>n+(+s.total||0),0),profit=revenue-investment;return{units:products.reduce((n,p)=>n+(+p.stock||0),0),investment,revenue,profit,margin:revenue?profit/revenue*100:0};},[products,sales]);
 const removeSale=async sale=>{if(!confirm(`Eliminar la venta de ${sale.productName}?`))return;const qty=+sale.quantity||0;if(!db){setProducts(xs=>xs.map(p=>p.id===sale.productId?{...p,stock:+p.stock+qty}:p));setSales(xs=>xs.filter(s=>s.id!==sale.id));return;}await runTransaction(db,async t=>{const pr=doc(db,'products',sale.productId),sr=doc(db,'sales',sale.id),snap=await t.get(pr);if(snap.exists())t.update(pr,{stock:(+snap.data().stock||0)+qty,updatedAt:serverTimestamp()});t.delete(sr);});};
 const changeSale=async(sale,qtyValue)=>{const qty=+qtyValue,delta=qty-(+sale.quantity||0);if(qty<1)return;if(!db){const p=products.find(x=>x.id===sale.productId);if(!p||delta>p.stock)return alert('Stock insuficiente');setProducts(xs=>xs.map(x=>x.id===sale.productId?{...x,stock:x.stock-delta}:x));setSales(xs=>xs.map(x=>x.id===sale.id?{...x,quantity:qty,total:qty*x.unitPrice,costTotal:qty*x.unitCost}:x));return;}await runTransaction(db,async t=>{const pr=doc(db,'products',sale.productId),sr=doc(db,'sales',sale.id),snap=await t.get(pr);if(!snap.exists()||delta>(+snap.data().stock||0))throw Error('Stock insuficiente');t.update(pr,{stock:(+snap.data().stock||0)-delta,updatedAt:serverTimestamp()});t.update(sr,{quantity:qty,total:qty*sale.unitPrice,costTotal:qty*sale.unitCost,updatedAt:serverTimestamp()});});};
 saleCrud={removeSale,changeSale};
 const shown=products.filter(p=>`${p.name} ${p.category} ${p.sku}`.toLowerCase().includes(search.toLowerCase()));
 const save=async form=>{const payload={...form,stock:+form.stock,cost:+form.cost,price:+form.price,updatedAt:serverTimestamp()};if(!db)setProducts(xs=>editing?xs.map(x=>x.id===editing.id?{...x,...payload}:x):[{id:crypto.randomUUID(),...payload},...xs]);else if(editing)await updateDoc(doc(db,'products',editing.id),payload);else await addDoc(collection(db,'products'),{...payload,createdAt:serverTimestamp()});setEditing(null);setProductOpen(false);};
 const remove=async p=>{if(!confirm(`¿Eliminar ${p.name}?`))return;if(!db)setProducts(xs=>xs.filter(x=>x.id!==p.id));else await deleteDoc(doc(db,'products',p.id));};
 const sell=async({productId,quantity})=>{const qty=+quantity,p=products.find(x=>x.id===productId);if(!p||qty<1||qty>p.stock)return;const sale={productId,productName:p.name,quantity:qty,unitPrice:p.price,unitCost:p.cost,total:qty*p.price,costTotal:qty*p.cost,createdAt:db?serverTimestamp():new Date()};if(!db){setProducts(xs=>xs.map(x=>x.id===p.id?{...x,stock:x.stock-qty}:x));setSales(xs=>[{id:crypto.randomUUID(),...sale},...xs]);}else await runTransaction(db,async t=>{const ref=doc(db,'products',p.id),snap=await t.get(ref);if(!snap.exists()||snap.data().stock<qty)throw Error('Stock insuficiente');t.update(ref,{stock:snap.data().stock-qty,updatedAt:serverTimestamp()});t.set(doc(collection(db,'sales')),sale);});setSaleOpen(false);};
 const nav=[['Resumen',LayoutDashboard],['Productos',Boxes],['Ventas',ShoppingBag],['Inversión',CircleDollarSign]];
 return <main><aside><div className="brand-logo"><img src={axinopLogo} alt="Axinop Technologies"/></div><p className="business">PANEL DE NEGOCIO</p>{nav.map(([n,I])=><button className={section===n?'nav active':'nav'} onClick={()=>setSection(n)} key={n}><I size={19}/>{n}</button>)}<div className="side-bottom"><span>Innovación bajo control.</span></div></aside><section className="content"><header><div><p className="eyebrow">{section==='Resumen'?'VISTA GENERAL':'GESTIÓN'}</p><h1>{section}</h1></div><button className="primary" onClick={()=>section==='Ventas'?setSaleOpen(true):setProductOpen(true)}><Plus size={18}/>{section==='Ventas'?'Registrar venta':'Nuevo producto'}</button></header>{!isFirebaseConfigured&&<div className="setup"><b>Modo demostración:</b> agrega Firebase en <code>.env</code> para guardar los cambios.</div>}{section==='Resumen'?<Dashboard products={products} sales={sales} metrics={metrics}/>:section==='Ventas'?<Sales sales={sales} onOpen={()=>setSaleOpen(true)}/>:section==='Inversión'?<Investment products={products} metrics={metrics}/>:<Products products={shown} search={search} setSearch={setSearch} onOpen={setDetail} onEdit={p=>{setEditing(p);setProductOpen(true);}} onDelete={remove}/>}</section>{productOpen&&<ProductForm value={editing||blank} onSave={save} onClose={()=>{setEditing(null);setProductOpen(false);}}/>}{saleOpen&&<SaleForm products={products} onSave={sell} onClose={()=>setSaleOpen(false)}/>} {detail&&<ProductDetail product={detail} sales={sales} onClose={()=>setDetail(null)}/>}</main>;
}
const Stat=({label,value,meta,icon})=><article className="stat"><div className="stat-icon">{icon}</div><p>{label}</p><h2>{value}</h2>{meta&&<small>{meta}</small>}</article>;
function Dashboard({products,sales,metrics}){return <><div className="mobile-summary-logo"><img src={axinopLogo} alt="Axinop Technologies"/></div><div className="hero"><div><span className="chip">HOY</span><h2>Todo en orden.</h2><p>Tu inventario y ventas en un solo lugar.</p></div><BarChart3 size={44}/></div><div className="stats"><Stat label="Inventario disponible" value={`${metrics.units} unidades`} icon="▦"/><Stat label="Inversión total" value={money.format(metrics.investment)} icon="◎"/><Stat label="Ventas acumuladas" value={money.format(metrics.revenue)} icon="↗"/><Stat label="Ganancia" value={money.format(metrics.profit)} meta={`${metrics.margin.toFixed(0)}% margen`} icon="✦"/></div><div className="two-cols"><article className="panel"><div className="panel-title"><div><p className="eyebrow">INVENTARIO</p><h3>Productos recientes</h3></div></div>{products.slice(0,4).map(p=><ProductRow p={p} key={p.id}/>)||<Empty text="Aún no tienes productos"/>}</article><article className="panel"><div className="panel-title"><div><p className="eyebrow">RENDIMIENTO</p><h3>Últimas ventas</h3></div></div>{sales.slice(0,4).map(s=><SaleRow s={s} key={s.id}/>)}{!sales.length&&<Empty text="Registra tu primera venta"/>}</article></div></>}
function Products({products,search,setSearch,onOpen,onEdit,onDelete}){return <><div className="toolbar"><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto, categoría o SKU"/></div><span>{products.length} productos</span></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.id} role="button" tabIndex="0" onClick={()=>onOpen(p)} onKeyDown={e=>e.key==='Enter'&&onOpen(p)}><ProductImage p={p}/><div className="card-body"><span className="tag">{p.category||'Sin categoría'}</span><h3>{p.name}</h3><p className="sku">SKU: {p.sku||'—'}</p><div className="price"><b>{money.format(p.price)}</b><span>Costo {money.format(p.cost)}</span></div><div className="card-footer"><span className={p.stock<=3?'stock warn':'stock'}>{p.stock} disponibles</span><div><button aria-label="Editar" onClick={e=>{e.stopPropagation();onEdit(p)}}><Pencil size={16}/></button><button aria-label="Eliminar" onClick={e=>{e.stopPropagation();onDelete(p)}}><Trash2 size={16}/></button></div></div></div></article>)}{!products.length&&<Empty text="No hay productos que mostrar"/>}</div></>}
function ProductImage({p}){return <div className="product-image">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<PackagePlus size={26}/>}</div>};function ProductRow({p}){return <div className="product-row"><ProductImage p={p}/><div><b>{p.name}</b><small>{p.category||'Sin categoría'} · SKU {p.sku||'—'}</small></div><span className={p.stock<=3?'stock warn':'stock'}>{p.stock} uds.</span><strong>{money.format(p.price)}</strong></div>};function SaleRow({s}){return <div className="sale-row"><div className="round">$</div><div><b>{s.productName}</b><small>{s.quantity} unidades</small></div><strong>{money.format(s.total)}</strong></div>};function Empty({text}){return <div className="empty"><ShoppingBag size={27}/><p>{text}</p></div>}
function Sales({sales,onOpen}){const [exportOpen,setExportOpen]=useState(false),[editingSale,setEditingSale]=useState(null);return <><article className="panel sales"><div className="panel-title"><div><p className="eyebrow">HISTORIAL</p><h3>Ventas registradas</h3></div><div className="sales-actions"><button className="secondary export-button" onClick={()=>setExportOpen(true)}>Exportar Excel</button><button className="primary small" onClick={onOpen}><Plus size={16}/>Nueva venta</button></div></div>{sales.map(s=><div className="sale-row sale-crud" key={s.id}><div className="round">$</div><div><b>{s.productName}</b><small>{s.quantity} unidades</small></div><strong>{money.format(s.total)}</strong><div className="sale-buttons"><button aria-label="Editar venta" onClick={()=>setEditingSale(s)}><Pencil size={15}/></button><button aria-label="Eliminar venta" onClick={()=>saleCrud.removeSale(s)}><Trash2 size={15}/></button></div></div>)}{!sales.length&&<Empty text="Aún no se han registrado ventas"/>}</article>{exportOpen&&<ExportModal sales={sales} onClose={()=>setExportOpen(false)}/>} {editingSale&&<EditSaleModal sale={editingSale} onClose={()=>setEditingSale(null)}/>}</>};function Investment({products,metrics}){return <><div className="stats"><Stat label="Inversión total" value={money.format(metrics.investment)} icon="◎"/><Stat label="Productos activos" value={products.filter(p=>p.stock>0).length} icon="▦"/><Stat label="Unidades disponibles" value={metrics.units} icon="↗"/><Stat label="Costo promedio" value={money.format(metrics.units?metrics.investment/metrics.units:0)} icon="✦"/></div><article className="panel sales"><h3>Desglose por producto</h3>{products.map(p=><div className="sale-row" key={p.id}><div className="round">{p.stock}</div><div><b>{p.name}</b><small>{p.stock} uds. × {money.format(p.cost)}</small></div><strong>{money.format(p.stock*p.cost)}</strong></div>)}</article></>}
function saleDate(s){return s.createdAt?.toDate?s.createdAt.toDate():s.createdAt?new Date(s.createdAt):null};function ExportModal({sales,onClose}){const today=new Date().toISOString().slice(0,10),[preset,setPreset]=useState('30'),[start,setStart]=useState(today),[end,setEnd]=useState(today);const download=e=>{e.preventDefault();const endDate=new Date(`${end}T23:59:59`),startDate=preset==='custom'?new Date(`${start}T00:00:00`):new Date(endDate);if(preset!=='custom')startDate.setDate(startDate.getDate()-Number(preset)+1);const filtered=sales.filter(s=>{const d=saleDate(s);return d&&d>=startDate&&d<=endDate});const total=filtered.reduce((n,s)=>n+(+s.total||0),0),cost=filtered.reduce((n,s)=>n+(+s.costTotal||0),0);const summary=XLSX.utils.aoa_to_sheet([['Reporte de ventas Axinop'],['Periodo',`${startDate.toLocaleDateString('es-MX')} - ${endDate.toLocaleDateString('es-MX')}`],['Ventas',filtered.length],['Ingresos',total],['Costo de ventas',cost],['Ganancia',total-cost]]);summary['!cols']=[{wch:22},{wch:28}];const rows=filtered.map(s=>({Fecha:saleDate(s),Producto:s.productName,Cantidad:s.quantity,'Precio unitario':s.unitPrice,'Costo unitario':s.unitCost,Ingresos:s.total,'Costo de ventas':s.costTotal,Ganancia:(+s.total||0)-(+s.costTotal||0)}));const details=XLSX.utils.json_to_sheet(rows);details['!cols']=[{wch:14},{wch:32},{wch:10},{wch:16},{wch:16},{wch:15},{wch:17},{wch:15}];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,summary,'Resumen');XLSX.utils.book_append_sheet(book,details,'Ventas');XLSX.writeFile(book,`reporte-ventas-${startDate.toISOString().slice(0,10)}-${end}.xlsx`);onClose()};return <Modal title="Exportar reporte de ventas" onClose={onClose}><form onSubmit={download}><label>Rango de fechas<select value={preset} onChange={e=>setPreset(e.target.value)}><option value="7">Últimos 7 días</option><option value="15">Quincena (15 días)</option><option value="30">Último mes</option><option value="90">Últimos 3 meses</option><option value="180">Últimos 6 meses</option><option value="365">Último año</option><option value="custom">Personalizado</option></select></label>{preset==='custom'&&<div className="form-grid"><Field label="Desde" type="date" value={start} onChange={e=>setStart(e.target.value)} required/><Field label="Hasta" type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></div>}<p className="export-note">El archivo incluirá una hoja de resumen y otra con el detalle de cada venta.</p><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Descargar Excel</button></div></form></Modal>}
function EditSaleModal({sale,onClose}){const [quantity,setQuantity]=useState(sale.quantity);return <Modal title="Modificar venta" onClose={onClose}><p className="export-note"><b>{sale.productName}</b><br/>Precio unitario: {money.format(sale.unitPrice)}</p><label>Cantidad vendida<input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><div className="modal-actions"><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" onClick={async()=>{await saleCrud.changeSale(sale,quantity);onClose();}}>Guardar cambios</button></div></Modal>}
function ProductDetail({product,sales,onClose}){const sold=sales.filter(s=>s.productId===product.id).reduce((n,s)=>n+(+s.quantity||0),0);return <Modal title={product.name} onClose={onClose}><div className="detail-head"><ProductImage p={product}/><div><span className="tag">{product.category||'Sin categoría'}</span><p className="sku">SKU: {product.sku||'—'}</p></div></div><div className="detail-grid"><div><small>Vendidos</small><b>{sold} unidades</b></div><div><small>Disponibles</small><b>{product.stock} unidades</b></div><div><small>Costo unitario</small><b>{money.format(product.cost)}</b></div><div><small>Precio de venta</small><b>{money.format(product.price)}</b></div></div>{product.sourceUrl?<a className="purchase-link" href={product.sourceUrl} target="_blank" rel="noreferrer">Ir a URL de compra <ExternalLink size={16}/></a>:<p className="no-link">Este producto no tiene URL de compra registrada.</p>}<div className="modal-actions"><button className="primary" onClick={onClose}>Cerrar</button></div></Modal>}
function ProductForm({value,onSave,onClose}){const [form,setForm]=useState(value),set=e=>setForm({...form,[e.target.name]:e.target.value});return <Modal title={value.id?'Editar producto':'Nuevo producto'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="form-grid"><Field label="Nombre" name="name" value={form.name} onChange={set} required/><Field label="Categoría" name="category" value={form.category} onChange={set}/><Field label="SKU" name="sku" value={form.sku} onChange={set}/><Field label="Disponibles" name="stock" type="number" min="0" value={form.stock} onChange={set}/><Field label="Costo unitario" name="cost" type="number" min="0" step=".01" value={form.cost} onChange={set}/><Field label="Precio de venta" name="price" type="number" min="0" step=".01" value={form.price} onChange={set}/></div><Field label="URL de imagen" name="imageUrl" value={form.imageUrl} onChange={set}/><Field label="URL de compra" name="sourceUrl" value={form.sourceUrl} onChange={set}/><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Guardar producto</button></div></form></Modal>};function SaleForm({products,onSave,onClose}){const [form,setForm]=useState({productId:products.find(p=>p.stock>0)?.id||'',quantity:1});return <Modal title="Registrar venta" onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(form)}}><label>Producto<select value={form.productId} onChange={e=>setForm({...form,productId:e.target.value})}>{products.map(p=><option value={p.id} disabled={!p.stock} key={p.id}>{p.name} — {p.stock} disponibles</option>)}</select></label><Field label="Cantidad vendida" type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Confirmar venta</button></div></form></Modal>};function Field({label,...props}){return <label>{label}<input {...props}/></label>};function Modal({title,onClose,children}){return <div className="backdrop"><div className="modal"><button className="close" onClick={onClose}><X size={20}/></button><h2>{title}</h2>{children}</div></div>}
function InvestmentDetails({products,metrics}){const rows=products.map(p=>{const related=investmentSales.filter(s=>s.productId===p.id),sold=related.reduce((n,s)=>n+(+s.quantity||0),0),soldCost=related.reduce((n,s)=>n+(+s.costTotal||0),0),availableCost=(+p.stock||0)*(+p.cost||0),purchased=(+p.stock||0)+sold;return{p,purchased,total:availableCost+soldCost};});return <><div className="stats"><Stat label="Inversión total" value={money.format(metrics.investment)} icon="◎"/><Stat label="Productos activos" value={products.filter(p=>p.stock>0).length} icon="▦"/><Stat label="Unidades disponibles" value={metrics.units} icon="↗"/><Stat label="Costo promedio" value={money.format(metrics.units?metrics.investment/metrics.units:0)} icon="✦"/></div><article className="panel investment-table"><div className="panel-title"><div><p className="eyebrow">INVERSIÓN ACUMULADA</p><h3>Desglose por producto</h3></div></div><div className="investment-head"><span>Producto</span><span>Piezas compradas</span><span>Costo unitario (impuestos)</span><span>Total</span></div>{rows.map(({p,purchased,total})=><div className="investment-row" key={p.id}><div><b>{p.name}</b><small>SKU: {p.sku||'—'}</small></div><span>{purchased}</span><span>{money.format(p.cost)}</span><strong>{money.format(total)}</strong></div>)}{!rows.length&&<Empty text="Añade productos para calcular tu inversión"/>}</article></>}
Investment = InvestmentDetails;
createRoot(document.getElementById('root')).render(<App/>);
